### ISSUE TITLE
Sans dependency

### ISSUE THREAD

**Issue by fxfactorial** [aantron/lambda-soup#1]
First, awesome! Thank you for doing this, it was lacking in OCaml world. 

Question, can you do this without using OCamlnet or unix dependency?

**Comment by aantron** [comment]
Yes. I am already looking into it :) The Ocamlnet dependency is somewhat unfortunate, since Ocamlnet is much more than an HTML parser, and takes a while to compile, and I, too, would like to avoid depending on `Unix` because I sometimes compile with `js_of_ocaml`, for example.

It looks like there are two main options.

- Use another library's parser. I don't know of a better one than Ocamlnet, however. Let me know if you do.
- Write a new library focused on just HTML parsing. I have been studying this since yesterday, and am going down this route absent more information. It will take some days or maybe even weeks, however. If you have any direct use for an HTML parser, please tell me what your requirements are. It can help me to design the right interface. I am currently aiming for something 2-level. The bottom level is a SAX-style interface that emits events. The top, optional level provides a DOM tree data structure built over that, for convenience.

**Comment by aantron** [comment]
Actually, let me first look into extracting Ocamlnet's parser and incorporating it, as a stop-gap measure. There is no reason by Lambda Soup should transitively depend on Unix.

**Comment by rgrinberg** [comment]
Is xmlm too level to implement the desired html parsing?

**Comment by aantron** [comment]
My impression based on the documentation is that it is too strict for even well-formed HTML, but I will examine it in more detail and try it out, along with whatever is in COW. Do you know of any other parsers out there?

**Comment by fxfactorial** [comment]
FWIW I had trouble getting xmlm to parse HTML since HTML is so much more lenient than xhtml

**Comment by rgrinberg** [comment]
Cow is xmlm based I believe so it should be no less strict.

**Comment by aantron** [comment]
Gentlemen, you may be interested in this: https://github.com/aantron/markup.ml.

**Comment by fxfactorial** [comment]
I don't understand, is this replacing lambda soup? I was fine with lambda soup.

**Comment by aantron** [comment]
No, it would be replacing Nethtml for use by Lambda Soup. It's a parser based on the HTML5 standard. I took from one of your messages that you had tried to parse HTML before, so I thought it may be of interest. Lambda Soup is at a higher level of abstraction than this new thing.

**Comment by fxfactorial** [comment]
@aantron excellent, much appreciated then!
