### ISSUE TITLE
Failure when parsing invalid HTML

### ISSUE THREAD

**Issue by yannham** [aantron/lambda-soup#10]
I tried to parse the github page of my project (https://github.com/yannham/mechaml/) using Lambdasoup, but I got an underlying unexpected error from Markup.ml. When I type in a REPL (utop)
 
`Soup.read_file "github.html" |> Soup.parse`

where github.html is a dump of the previously given github page, I get

> Exception: Failure "require_current_element: None"

While I expected Lambdasoup and Markup.ml to fail quietly

 on invalid HTML5, or at least not to fail with an uncaught exception.

[Here](http://yago.gb2n.org/github-lambdasoup.html) is a snapshot code of the incriminated version of the page

**Comment by aantron** [comment]
Thanks. This is an internal error in Markup.ml that needs to be fixed.

This is due to wrong handling of an unmatched `</form>` tag in the (ill-formed) HTML input.

I want to note that Markup.ml should not exactly fail quietly, more like report the bad tag to `~report` and then recover in a certain way – there is a specific behavior [required by HTML5](https://www.w3.org/TR/html5/syntax.html#parsing-main-inbody) (see 'An end tag whose tag name is "form"'), so I hesitate to call the correct behavior a failure.

**Comment by aantron** [comment]
This should be fixed now (in Markup.ml `master`). Sorry about the delay – I actually wrote most of this commit back in March, but then I faced making a slightly ugly tradeoff due to the specification, which assumes a DOM-building parser, not being fully compatible with streaming parsing. While thinking about how to resolve that, I eventually got swamped by other work. See the commit message for some detail on what I chose – but it's ultimately it's just some comments on esoteric HTML error recovery behavior.
